# ===================================
#  Import/Export Behavior Config
# ===================================

export:
    title: Export Mall orders
    modelClass: Voilaah\MallStats\Models\OrderExport
    list: $/voilaah/mallstats/models/orderexport/columns_export.yaml
    redirect: voilaah/mallstats/exports
    fileName: orders.csv
