# ===================================
#  Import/Export Behavior Config
# ===================================

export:
    title: Export Mall sales
    modelClass: Voilaah\MallStats\Models\SalesExport
    list: $/voilaah/mallstats/models/salesexport/columns_export.yaml
    redirect: voilaah/mallstats/exports
    fileName: sales.csv
